name: Windows (Latest) CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:

jobs:
  windows-latest:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: CMake build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 17 2022" -A x64 -DWARNINGS_AS_ERRORS=ON
          cmake --build build --config Debug
