name: Windows (Latest) CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:

jobs:
  windows-latest:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Conditional check for code changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - '**/*.c'
              - '**/*.cpp'
              - '**/*.h'
              - '**/*.hpp'
              - '**/*.hpp.in'
              - '**/*.rc.in'
              - '**/CMakeLists.txt'
              - '.github/workflows/**'
      - name: CMake build
        if: steps.changes.outputs.src == 'true'
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 17 2022" -A x64 -DWARNINGS_AS_ERRORS=ON
          cmake --build build --config Debug
